name: AziRouge
version: '${version}'
main: net.azisaba.aziRouge.AziRouge
description: Roguelike dungeon generator with external schematic templates.
api-version: '1.21'
softdepend:
  - WorldEdit
commands:
  azirouge:
    description: ダンジョン生成とゲームセッション管理を行います
    usage: /azirouge <start|end|generate|reload|debug|author>
    permission: azirouge.command
permissions:
  azirouge.command:
    description: AziRouge のコマンド利用権限
    default: op
  azirouge.start:
    description: AziRouge のゲームセッション開始権限
    default: op
  azirouge.end:
    description: AziRouge のゲームセッション終了権限
    default: op
  azirouge.command.reload:
    description: AziRouge の設定再読込権限
    default: op
  azirouge.command.debug:
    description: AziRouge のデバッグ切替権限
    default: op
  azirouge.command.generate:
    description: AziRouge のダンジョン生成権限
    default: op
  azirouge.command.author:
    description: AziRouge のゲーム内テンプレート編集権限
    default: op
